version: '3.4'

services:
  help:
    image: help
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8085:8085
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
