version: "3.9"

services:
  nocodb-seed:
    build: .
    container_name: nocodb-seed
    ports:
      - "8085:8085"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
